# Generated by Django 5.2 on 2025-04-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='gallery/thumbs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
