# Generated by Django 5.2 on 2025-04-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
