# Generated by Django 5.1.7 on 2025-04-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=250401, max_length=10, verbose_name='Телефонен номер'),
            preserve_default=False,
        ),
    ]
