# Generated by Django 5.2 on 2025-04-02 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('prototype', 'Прототип'), ('figure', 'Фигурка'), ('mechanical', 'Механична част'), ('other', 'Друго')], default='other', max_length=50)),
                ('model_file', models.FileField(upload_to='3d_models/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='model_previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models3d', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
