# Generated by Django 5.1.7 on 2025-03-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='category',
            field=models.CharField(choices=[('prototype', 'Прототип'), ('figure', 'Фигурка'), ('mechanical', 'Механична част'), ('other', 'Друго')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='model3d',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='model_previews/'),
        ),
    ]
