# Generated by Django 5.2 on 2025-04-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='personal_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
