# Generated by Django 5.2 on 2025-04-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_personalization',
            field=models.BooleanField(default=False),
        ),
    ]
