# Generated by Django 5.2 on 2025-04-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_allow_personalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='personal_image',
            field=models.ImageField(blank=True, null=True, upload_to='personal_uploads/', verbose_name='Качено изображение'),
        ),
    ]
