# Generated by Django 5.2 on 2025-04-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_personal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='require_image_upload',
            field=models.BooleanField(default=False, verbose_name='Изисква изображение от потребителя'),
        ),
    ]
